package com.apphance.ameba

import org.gradle.api.Project

enum ProjectBaseProperty {
	
        PROJECT_NAME(false, 'project.name', 'Name of the project'),
        PROJECT_ICON_FILE(false, "project.icon.file", 'Path to project icon file'),
        PROJECT_URL(false, 'project.url.base', 'Project url'),
        PROJECT_DIRECTORY(false, 'project.directory.name', 'Name of project directory'),
        PROJECT_LANGUAGE(false, 'project.language', 'Language of project'),
        PROJECT_COUNTRY(false, 'project.country', 'Project country');
		
		private final boolean optional
		private final String name
		private final String description
		
		ProjectBaseProperty(boolean optional, String name, String description) {
			this.optional = optional
			this.name = name
			this.description = description
		}
		
		public boolean isOptional() {
			return optional
		}
		
		public String getName() {
			return name
		}
		
		public String getDescription() {
			return description
		}

		public static String printProperties(Project project, boolean useComments) {
			
			String s = """###########################################################
# Project properties
###########################################################\n"""
			if (useComments == false) {
				s = """###########################################################
# Generated by Ameba by running
#    gradle prepareSetup
# You can modify the file manually.
# Or you can re-run the prepareSetup command
# in case you want to be guided how to change it
###########################################################\n""" + s
			}
			for (ProjectBaseProperty property : ProjectBaseProperty.values()) {
				String comment = '# ' + property.getDescription()
				String propString = property.getName() + '='
				if (property.isOptional()) {
					comment = comment + ' [optional]'
				} else {
					comment = comment + ' [required]'
				}
				if (project.hasProperty(property.getName())) {
					propString = propString +  project[property.getName()]
				}
	
				if (useComments == true) {
					s += comment + '\n'
				}
				s += propString + '\n'
			}
			return s
		}
}
